### ISSUE TITLE
npm start 失敗

### ISSUE THREAD

**Issue by nondayo** [nondayo/my_webpack#1]
做到[文章](https://medium.com/@toumasaya/webpack-%E5%85%A5%E9%96%80-6e53ae59222d)中的
```
…
rules: [
    {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
            plugins: ['transform-runtime'],
            presets: ['es2015']
        }
    }
]
…
```
但是執行 `npm start` 失敗

log
```
[~/Desktop/myproject] (master) 0h2m $ npm start

> myproject@1.0.0 start /Users/YLibrarian/Desktop/myproject
> npm run build -s && npm run execute -s

Hash: b1a59b2ab184bc521059
Version: webpack 4.31.0
Time: 534ms
Built at: 05/15/2019 10:12:00 PM
 1 asset
Entrypoint main = bundle.js
[0] ./src/main.js 1.51 KiB {0} [built] [failed] [1 error]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./src/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "es2015" relative to directory "/Users/YLibrarian/Desktop/myproject/src"
    at /Users/YLibrarian/Desktop/myproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/YLibrarian/Desktop/myproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/YLibrarian/Desktop/myproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/YLibrarian/Desktop/myproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/YLibrarian/Desktop/myproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/YLibrarian/Desktop/myproject/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/YLibrarian/Desktop/myproject/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/YLibrarian/Desktop/myproject/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/YLibrarian/Desktop/myproject/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/YLibrarian/Desktop/myproject/node_modules/babel-loader/lib/index.js:173:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! myproject@1.0.0 start: `npm run build -s && npm run execute -s`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the myproject@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/YLibrarian/.npm/_logs/2019-05-15T14_12_00_394Z-debug.log
```

**Comment by nondayo** [comment]
```
options: {
            plugins: ['transform-runtime'],
            presets: ['es2015']
        }
```
這段拿掉就沒事了......
